# -*- coding: utf-8 -*-
import customtkinter, threading, os, gc, time
from tkinter import filedialog
from ..utils import base_functions as bf

class MosaicNormalFrame(customtkinter.CTkFrame):
    def __init__(self, master):
        super().__init__(master)

        # Initialisation
        self.file_input_path=None # Placeholder for the input path
        self.file_export_path=None # Placeholder for the export path

        # Grid geometry weights
        self.grid_columnconfigure(0, weight=1)  # Spread the selected file/folder
        self.grid_rowconfigure((0,1,2,3), weight=1)  # Push options + conversion to bottom.
        
        # Row 0, info text
        self.info=customtkinter.CTkLabel(
            self, 
            text='Process an EMD mosaic' +
            '\nExports elemental maps as generated by Velox from a folder with .emd files',
            anchor='center')
        self.info.grid(row=0, column=0, columnspan=4, sticky='new', pady=5, padx =5)

        # Row 1, selected file (input)
        self.file_input=customtkinter.CTkLabel(
            self,
            text='Input folder',
            anchor='w')
        self.file_input.grid(row=1, column=0, sticky='w', pady=5, padx =5)

        # Row 1, browse button (input)
        self.browse_input=customtkinter.CTkButton(
            self,
            text='Browse',
            command=self.browse_input)
        self.browse_input.grid(row=1, column=3, sticky='ew', pady=5, padx =5)
        
        # Row 2, selected folder (export)
        self.file_export=customtkinter.CTkLabel(
            self,
            text='Export folder',
            anchor='w')
        self.file_export.grid(row=2, column=0, sticky='w', pady=5, padx =5)

        # Row 2, browse button (export)
        self.browse_export=customtkinter.CTkButton(
            self,
            text='Browse',
            command=self.browse_export)
        self.browse_export.grid(row=2, column=3, sticky='ew', pady=5, padx =5)
        
        # Row 3, empty weighted row to force the options & conversion down in the frame

        # Row 4, invert HAADF option
        self.options_invert=customtkinter.CTkCheckBox(
            self,
            text='Invert HAADF')
        self.options_invert.grid(row=4, column =1, sticky='ew', pady =5, padx=5)

        # Row 5, normalize option
        self.options_norm=customtkinter.CTkCheckBox(
            self,
            text='Normalize',
            command=lambda: self.force_default()) # trigger: if unchecked, turn off blur and set dtype to 16-bit.
        self.options_norm.grid(row=5, column=1, sticky='ew', pady=5, padx =5)
        
        # Row 5, normalize minimum parameter - default 0.5%
        self.options_norm_min=customtkinter.CTkEntry(
            self,
            placeholder_text='Min (Default 0.5%)')
        self.options_norm_min.grid(row=5, column=2, sticky='ew', pady=5, padx =5)

        # Row 5, normalize maximum parameter - default 99.5%
        self.options_norm_max=customtkinter.CTkEntry(
            self,
            placeholder_text='Max (Default 99.5%)')
        self.options_norm_max.grid(row=5, column=3, sticky='ew', pady=5, padx =5)
        
        # Row 6, Gaussian blur option
        self.options_blur=customtkinter.CTkCheckBox(
            self,
            text='Gaussian blur',
            command=lambda: self.force_normalize()) # trigger: if checked, force normalize ON
        self.options_blur.grid(row=6, column=1, sticky='ew', pady=5, padx =5)

        # Row 6, Gaussian blur sigma parameter - default 1
        self.options_blur_sigma=customtkinter.CTkEntry(
            self,
            placeholder_text='Sigma (Default 1)')
        self.options_blur_sigma.grid(row=6, column=2, columnspan=2, sticky='ew', pady=5, padx =5)

        # Row 7, room for pop-up information
        self.popup=customtkinter.CTkLabel(
            self,
            text=None,
            anchor='s')
        self.popup.grid(row=7, column=0, columnspan=4, sticky='wes', pady=5, padx =5)        

        # Row 8, convert button
        customtkinter.CTkButton(
            self,
            text='Convert',
            anchor='s',
            command=self.convert
        ).grid(row=8, column=0,  columnspan=3, sticky='wes', pady=5, padx =5)
        
        # Row 8, bit-depth selection
        self.options_dtype=customtkinter.CTkOptionMenu(
            self,
            values=['16-bit', '8-bit'],
            anchor='s',
            command=lambda value: self.force_normalize()) # trigger: if checked, force normalize ON
        self.options_dtype.grid(row=8, column=3, sticky='wes', pady=5, padx =5)
        
        # Row 9, indeterminate progress bar
        self.progress=customtkinter.CTkProgressBar(
            self, 
            mode='indeterminate',
            height=5,
            corner_radius=1,
            progress_color='green')
        self.progress.grid(row=9, column=0, columnspan=4, sticky='wes', pady=5, padx =5)
        self.progress.stop()

    def browse_input(self):
        path=filedialog.askdirectory()
        if path:
            self.file_input_path=path
            self.file_input.configure(text=path)
    
    def browse_export(self):
        path=filedialog.askdirectory()
        if path:
            self.file_export_path=path
            self.file_export.configure(text=path)

    def convert(self):
        start_time = time.time()
        def task():
            self.progress.start()
            bf.processMosaicNormal(self.file_input_path, 
                             self.file_export_path,
                             self.options_invert.get(),
                             self.options_norm.get(),
                             self.options_norm_min.get(),
                             self.options_norm_max.get(),
                             self.options_blur.get(),
                             self.options_blur_sigma.get(),
                             self.options_dtype.get()
                             )
            self.progress.stop()
            self.progress.set(1)
            self.popup.configure(text='Completed! \n'+ 
                                 f'Took {(time.time() - start_time):.2f} seconds.')
            gc.collect()
        if not self.file_export_path or not self.file_input_path:
            self.popup.configure(text='Select a file & folder first!')
            return    
        
        threading.Thread(target=task, daemon=True).start()
        
    def force_normalize(self):
        if self.options_blur.get() == 1 or self.options_dtype.get() == '8-bit':
            self.options_norm.select()
            self.popup.configure(text='')

    def force_default(self):
        if self.options_norm.get() == 0:
            if self.options_blur.get() == 1 and self.options_dtype.get() == '8-bit':
                self.options_blur.deselect()
                self.options_dtype.set('16-bit')
                self.popup.configure(text='WARNING: default settings restored!\n' + 
                                     'Blurring and conversion to 8-bit both require normalization')               
            elif self.options_blur.get() == 1:
                self.options_blur.deselect()
                self.popup.configure(text='WARNING: default settings restored!\n' + 
                                     'Blurring requires normalization')   
            elif self.options_dtype.get() == '8-bit':
                self.options_dtype.set('16-bit')
                self.popup.configure(text='WARNING: default settings restored!\n' + 
                                     'Conversion to 8-bit requires normalization')
        else:
            self.popup.configure(text='')   
    
        
    def reset(self):
        self.file_input_path=None
        self.file_export_path=None
        self.file_input.configure(text='Input folder')
        self.file_export.configure(text='Export folder')
        self.popup.configure(text='')
        self.options_invert.deselect()
        self.options_norm.deselect()        
        self.options_blur.deselect()
        self.options_dtype.set('16-bit')
        

